import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

type RouteParams = { params: Promise<{ id: string }> };

function money(n: number) {
  return `R ${n.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function formatDate(value: Date | string | null) {
  if (!value) return "—";
  return new Date(value).toLocaleDateString("en-ZA", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export async function GET(_req: Request, { params }: RouteParams) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;

  const invoice = await prisma.invoice.findFirst({
    where: { id, userId: session.user.id },
    include: {
      client: { select: { id: true, name: true, email: true, company: true } },
      project: { select: { id: true, name: true } },
      lineItems: true,
      user: { select: { name: true, email: true } },
    },
  });

  if (!invoice) {
    return NextResponse.json({ error: "Invoice not found" }, { status: 404 });
  }

  // Calculate totals
  const subtotal = invoice.lineItems.reduce((sum, item) => {
    const qty = Number(item.quantity) || 0;
    const price = Number(item.unitPrice) || 0;
    return sum + qty * price;
  }, 0);
  const taxRate = Number(invoice.taxRate) || 0;
  const tax = subtotal * (taxRate / 100);
  const total = subtotal + tax;

  // Build PDF in memory
  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const chunks: Buffer[] = [];

  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const pdfPromise = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  // Header
  doc
    .fontSize(22)
    .fillColor("#111111")
    .text("INVOICE", { align: "left" });

  doc
    .fontSize(10)
    .fillColor("#555555")
    .text(invoice.invoiceNumber, { align: "left" })
    .moveDown(0.5);

  // Status + dates
  doc
    .fontSize(10)
    .fillColor("#333333")
    .text(`Status: ${invoice.status}`)
    .text(`Issue date: ${formatDate(invoice.issueDate)}`)
    .text(`Due date: ${formatDate(invoice.dueDate)}`)
    .moveDown();

  // Bill to
  doc.fontSize(11).fillColor("#111111").text("Bill To", { underline: true });
  doc.fontSize(10).fillColor("#333333");
  if (invoice.client) {
    doc.text(invoice.client.name);
    if (invoice.client.company) doc.text(invoice.client.company);
    if (invoice.client.email) doc.text(invoice.client.email);
  } else {
    doc.text("—");
  }
  doc.moveDown();

  if (invoice.project) {
    doc.fontSize(10).fillColor("#555555").text(`Project: ${invoice.project.name}`);
    doc.moveDown();
  }

  // Line items table header
  const tableTop = doc.y + 10;
  const colDesc = 50;
  const colQty = 320;
  const colPrice = 380;
  const colTotal = 460;

  doc
    .fontSize(9)
    .fillColor("#666666")
    .text("Description", colDesc, tableTop)
    .text("Qty", colQty, tableTop)
    .text("Unit Price", colPrice, tableTop)
    .text("Amount", colTotal, tableTop);

  doc
    .moveTo(50, tableTop + 15)
    .lineTo(545, tableTop + 15)
    .strokeColor("#cccccc")
    .stroke();

  let y = tableTop + 25;

  invoice.lineItems.forEach((item) => {
    const qty = Number(item.quantity) || 0;
    const price = Number(item.unitPrice) || 0;
    const lineTotal = qty * price;

    doc
      .fontSize(10)
      .fillColor("#222222")
      .text(item.description, colDesc, y, { width: 250 })
      .text(String(qty), colQty, y)
      .text(money(price), colPrice, y)
      .text(money(lineTotal), colTotal, y);

    y += 20;
    if (y > 700) {
      doc.addPage();
      y = 50;
    }
  });

  // Totals
  y += 15;
  doc
    .moveTo(350, y)
    .lineTo(545, y)
    .strokeColor("#cccccc")
    .stroke();

  y += 12;
  doc.fontSize(10).fillColor("#555555");
  doc.text("Subtotal", 350, y);
  doc.text(money(subtotal), colTotal, y);

  y += 16;
  doc.text(`Tax (${taxRate}%)`, 350, y);
  doc.text(money(tax), colTotal, y);

  y += 18;
  doc.fontSize(12).fillColor("#111111").font("Helvetica-Bold");
  doc.text("Total", 350, y);
  doc.text(money(total), colTotal, y);
  doc.font("Helvetica");

  // Notes
  if (invoice.notes) {
    y += 40;
    doc.fontSize(10).fillColor("#555555").text("Notes", 50, y);
    y += 14;
    doc.fontSize(9).fillColor("#333333").text(invoice.notes, 50, y, {
      width: 495,
    });
  }

  // Footer
  doc
    .fontSize(8)
    .fillColor("#999999")
    .text(
      `Generated by Tech Alchemy CRM • ${new Date().toLocaleString("en-ZA")}`,
      50,
      780,
      { align: "center", width: 495 }
    );

  doc.end();

  const pdfBuffer = await pdfPromise;

  return new NextResponse(pdfBuffer, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${invoice.invoiceNumber}.pdf"`,
      "Cache-Control": "no-store",
    },
  });
}
